parameters:
    service.client.curl.class: Agazzi\RestClientAuthenticatorBundle\Services\CurlService
    service.client.crypter.class: Agazzi\RestClientAuthenticatorBundle\Services\CrypterService
    service.client.user.class: Agazzi\RestClientAuthenticatorBundle\Services\UserService

services:
    service.client.curl:
        class: %service.client.curl.class%
        calls:
            - [setContainer, [@service_container]]
    service.client.crypter:
        class: %service.client.crypter.class%
        calls:
            - [setContainer, [@service_container]]
    service.client.user:
        class: %service.client.user.class%
        calls:
            - [setContainer, [@service_container]]
