parameters:
    service.client.curl.class: Agazzi\RestClientAuthenticatorBundle\Services\CurlService
    service.client.crypter.class: Agazzi\RestClientAuthenticatorBundle\Services\CrypterService
    service.client.user.class: Agazzi\RestClientAuthenticatorBundle\Services\UserService
    service.client.api.class: Agazzi\RestClientAuthenticatorBundle\Services\ApiService
    api.url: 'http://api.nativgaming.com'

services:
    service.client.curl:
        class: %service.client.curl.class%
        calls:
            - [setContainer, [@service_container]]
    service.client.crypter:
        class: %service.client.crypter.class%
        calls:
            - [setContainer, [@service_container]]
    service.client.user:
        class: %service.client.user.class%
        calls:
            - [setContainer, [@service_container]]
    service.api:
        class: %service.client.api.class%
        calls:
            - [setContainer, [@service_container]]
